# .github/workflows/jules-fix.yml
# Drop this into ANY repo with AGENTS.md to enable issue-triggered Jules fixes
# Requires: JULES_API_KEY secret

name: Jules Auto-Fix
on:
  issues:
    types: [labeled]
  workflow_dispatch:
    inputs:
      task:
        description: 'Task description for Jules'
        required: true

jobs:
  jules-fix:
    if: >
      github.event_name == 'workflow_dispatch' ||
      github.event.label.name == 'jules-fix'
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Clone DocMaintainer tools
        run: git clone --depth 1 https://github.com/FuMancho/DocMaintainer.git /tmp/DocMaintainer

      - name: Build task description
        id: task
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "prompt=${{ github.event.inputs.task }}" >> $GITHUB_OUTPUT
          else
            ISSUE_TITLE="${{ github.event.issue.title }}"
            ISSUE_NUM="${{ github.event.issue.number }}"
            echo "prompt=Fix issue #${ISSUE_NUM}: ${ISSUE_TITLE}. Read AGENTS.md for project context and constraints." >> $GITHUB_OUTPUT
          fi

      - name: Trigger Jules
        env:
          JULES_API_KEY: ${{ secrets.JULES_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python /tmp/DocMaintainer/scripts/trigger_jules.py \
            --repo ${{ github.event.repository.name }} \
            --auto-merge \
            --poll-interval 60 \
            --timeout 3600
